# Generated by Django 2.1 on 2021-10-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=25, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('objet', models.TextField()),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('numero_enregistrement', models.CharField(max_length=25)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('est_traite', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Destinataire_Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_destinataire', to='App_Courrier.Model_Courrier')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Document_Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_document', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Exped_Destinataire',
            fields=[
                ('model_personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Configuration.Model_Personne')),
            ],
            bases=('App_Configuration.model_personne',),
        ),
        migrations.CreateModel(
            name='Model_Nature_Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Type_Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='model_document_courrier',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_courr', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_document_courrier',
            name='courrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_docs', to='App_Courrier.Model_Courrier'),
        ),
        migrations.AddField(
            model_name='model_destinataire_courrier',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataire_courrier', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediteur_courriers', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nature_courriers', to='App_Courrier.Model_Nature_Courrier'),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_courriers', to='App_Courrier.Model_Type_Courrier'),
        ),
    ]
