# Generated by Django 2.1 on 2021-02-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('symbole', models.CharField(blank=True, max_length=5, null=True)),
                ('est_actif', models.BooleanField(default=False)),
                ('est_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Droit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.CharField(max_length=50)),
                ('profils', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('code_telephone', models.CharField(max_length=5)),
                ('code_pays', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='App_Configuration.Model_Place')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('est_profil_caisse', models.BooleanField(default=False)),
                ('est_total_caisse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Taux_du_jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('taux', models.FloatField()),
                ('est_actif', models.BooleanField(default=False)),
                ('est_caisse', models.BooleanField(default=False)),
                ('est_coffre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Employe',
            fields=[
                ('model_personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Configuration.Model_Personne')),
                ('poste', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('est_caissier', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_employe', to='App_Configuration.Model_Profil')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personne', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('App_Configuration.model_personne',),
        ),
        migrations.AddField(
            model_name='model_taux_du_jour',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_taux', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_taux_du_jour',
            name='devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devise_taux', to='App_Configuration.Model_Devise'),
        ),
        migrations.AddField(
            model_name='model_personne',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_creees', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_personne',
            name='commune_quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to='App_Configuration.Model_Place'),
        ),
        migrations.AddField(
            model_name='model_droit',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_droit', to='App_Configuration.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_droit',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droit_menu', to='MainApp.Model_Menu'),
        ),
        migrations.AddField(
            model_name='model_devise',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_devise', to='App_Configuration.Model_Personne'),
        ),
    ]
