# Generated by Django 2.1 on 2023-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_personne',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
