# Generated by Django 2.1 on 2021-09-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MakutaTransfert', '0008_auto_20210908_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resolu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Type_Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='model_reclamation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_reclamations', to='App_Support.Model_Type_Reclamation'),
        ),
        migrations.AddField(
            model_name='model_reclamation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reclamation', to='MakutaTransfert.Model_Utilisateur'),
        ),
    ]
