# Generated by Django 2.1 on 2021-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_reclamation',
            name='transfert',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
