# Generated by Django 2.1 on 2021-09-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Support', '0003_model_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('nom_fichier', models.CharField(max_length=500)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichier_reclemation', to='App_Support.Model_Reclamation')),
            ],
        ),
    ]
