# Generated by Django 2.1 on 2021-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Support', '0004_model_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_fichier',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
