# Generated by Django 2.1 on 2021-12-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/upload_recrutement/diplomes/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Candidat',
            fields=[
                ('model_personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App_Configuration.Model_Personne')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('App_Configuration.model_personne',),
        ),
        migrations.CreateModel(
            name='Model_Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('dateinscrit', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='static/upload_recrutement/% Y/% m/% d/')),
                ('motivation', models.FileField(upload_to='static/upload_recrutement/% Y/% m/% d/')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_auteur', to='App_Configuration.Model_Personne')),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_candidat', to='App_Recutement.Model_Candidat')),
                ('diplome', models.ManyToManyField(to='App_Recutement.DiplomaFile')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('titre', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('datepublish', models.DateTimeField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=50, null=True)),
                ('typecontrat', models.CharField(blank=True, max_length=50, null=True)),
                ('dateclose', models.DateTimeField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('proccess', models.CharField(blank=True, max_length=50, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('tache', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offre_auteur', to='App_Configuration.Model_Personne')),
            ],
        ),
        migrations.AddField(
            model_name='model_candidature',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_offre', to='App_Recutement.Model_Offre'),
        ),
    ]
