# Generated by Django 2.1 on 2021-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_candidature',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en cours'), (2, 'annuler'), (3, 'attente'), (4, 'inconnu')], null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en cours'), (2, 'annuler'), (3, 'attente'), (4, 'inconnu')], null=True),
        ),
    ]
