# Generated by Django 2.1 on 2021-12-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0002_auto_20211220_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='model_candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='model_candidature',
            name='motivation',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
