# Generated by Django 2.1 on 2021-12-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0003_auto_20211224_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_candidature',
            name='auteur',
        ),
    ]
