# Generated by Django 2.1 on 2021-12-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0004_remove_model_candidature_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_candidature',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en attente du verification'), (2, 'accepté'), (3, 'décliner')], null=True),
        ),
    ]
