# Generated by Django 2.1 on 2021-12-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0005_auto_20211228_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_offre',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en cours'), (2, 'cloturer')], null=True),
        ),
    ]
