# Generated by Django 2.1 on 2023-02-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0006_auto_20211230_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Domaine_Recrutement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Poste_Recrutement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domaines_poste', to='App_Recutement.Model_Domaine_Recrutement')),
            ],
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='entreprise',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='localisation',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='proccess',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='qualification',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='reference',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='responsable',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en cours'), (2, 'cloturée')], null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='titre',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='typecontrat',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
