# Generated by Django 2.1 on 2023-02-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0007_auto_20230213_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_candidature',
            old_name='cv',
            new_name='path_cv2',
        ),
        migrations.AddField(
            model_name='model_candidature',
            name='est_depot_cv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_candidature',
            name='path_cv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='model_candidat',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poste_candidat', to='App_Recutement.Model_Poste_Recrutement'),
        ),
    ]
