# Generated by Django 2.1 on 2023-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0008_auto_20230220_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_candidature',
            name='path_cv2',
            field=models.FileField(blank=True, null=True, upload_to='CV/DEPOT'),
        ),
        migrations.AlterField(
            model_name='model_candidature',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'en attente du verification'), (2, 'accepté'), (3, 'décliner'), (3, 'cv deposé')], null=True),
        ),
    ]
