# Generated by Django 2.1 on 2023-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0009_auto_20230220_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_candidature',
            name='deja_ouvert',
            field=models.BooleanField(default=False),
        ),
    ]
