# Generated by Django 2.1 on 2023-02-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0010_model_candidature_deja_ouvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_candidature',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_candidat', to='App_Recutement.Model_Candidat'),
        ),
        migrations.AlterField(
            model_name='model_candidature',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_offre', to='App_Recutement.Model_Offre'),
        ),
    ]
