# Generated by Django 2.1 on 2023-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recutement', '0011_auto_20230227_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_offre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='proccess',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_offre',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
